services:
  - type: web
    name: website-frontend
    env: node
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: website-db
          property: connectionString
      - key: NEXT_PUBLIC_APP_URL
        value: https://website-frontend.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: SKIP_TYPESCRIPT_CHECK
        value: true

databases:
  - name: website-db
    databaseName: website
    user: website_admin
    plan: free 