services:
  # Frontend Next.js Webservice
  - type: web
    name: website-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://creativedesign.onrender.com
      - key: NEXT_PUBLIC_BASE_URL
        value: https://creativedesign.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: website-db
          property: connectionString
      - key: NEXT_TELEMETRY_DISABLED
        value: 1

databases:
  # PostgreSQL Datenbank für die Anwendung
  - name: website-db
    plan: free
    ipAllowList: [] 